### ISSUE TITLE
filepath erro？

### ISSUE THREAD

**Issue by xqzc000** [objectbox/objectbox-examples#52]
io.objectbox.exception.DbException: Could not create directory: /objectbox
        at io.objectbox.BoxStore.getCanonicalPath(BoxStore.java:253)
        at io.objectbox.BoxStore.<init>(BoxStore.java:200)
        at io.objectbox.BoxStoreBuilder.build(BoxStoreBuilder.java:383)

**Comment by xqzc000** [comment]
hi,
my code like this: MyObjectBox.builder().build().

logcat show erro：io.objectbox.exception.DbException: Could not create directory: /objectbox.


then change code as fllow:
MyObjectBox.builder().directory(context.getFilesDir()).build()，the erro is gone.

but i don't know why,can this be fixed?

**Comment by greenrobot-team** [comment]
@xqzc000 Are you on Android? Try using
```
MyObjectBox.builder()
                .androidContext(context.getApplicationContext())
                .build();
```
instead.

See https://docs.objectbox.io/getting-started#core-initialization for details.
-Uwe

**Comment by greenrobot-team** [comment]
Otherwise make sure that you have write permissions on the folder you want to create the database in.

**Comment by greenrobot-team** [comment]
Closing this issue due to inactivity. :zzz: Please re-open with more details or submit a new issue to https://github.com/objectbox/objectbox-java/issues/.
